### PR TITLE
Handle canceled conversation for pam_chauthtok

### PR DESCRIPTION
**Pull request by hoehnth**
Use case: password for an user is expired and changed on next login etc. with pam_chauthtok.
If conversation is canceled in pam application, pam_conv() will return with PAM_CONV_ERR.
But pam_pwquality does not honor the return value and continues for loop.
So pam_conv() gets repeated password prompts and error messages as many times as the configured "retry" option which is annoying in pam application, especially with a high retry value.

### CODE REVIEW

**Comment by hoehnth** [comment]
Test application for pam_conv cancel:
[pam_test.c](https://gist.github.com/hoehnth/fa60459e134ec26a54a6145152c4366e)

gcc -lpam -o pam_test -c pam_test.c

Then set password expired for foobar:
passwd -e foobar

Start ./pam_test foobar login
and enter old password (to enter pam_chauthtok), then cancel pam conversation with empty password in new password prompt.

**Comment by t8m** [comment]
I fixed it a little bit differently.

**Comment by hoehnth** [comment]
yeah, looks fine.

now my PR is gone :-(

**Comment by t8m** [comment]
Sorry for that :-) I figured out that it would be easier for me to actually do the patch myself than explain to you all the changes you would have to do for me to accept it.

**Pull request closed without merging**
